# Generated by Django 5.1.1 on 2024-11-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chattings.createtopic'),
        ),
    ]
