# Generated by Django 5.1.1 on 2024-11-05 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_chats_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chattings.department'),
        ),
        migrations.AddField(
            model_name='replies',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chattings.createtopic'),
        ),
    ]
